name: urlspliter
description: A starting point for Dart libraries or applications.
version: 1.0.0+1
homepage: https://github.com/ipconfiger/UrlSpliter

environment:
  sdk: '>=3.1.4 <4.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
